steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'festbuzzzz-mvp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,ADMIN_EMAIL=crwdctrl.in@gmail.com,ADMIN_PASSWORD=CrwdCtrl0430,JWT_SECRET=Yd9n#2@zC5f*1R!e$gT7xP0vLqWm^KsA,MONGODB_URI=mongodb+srv://karan_lol:jadhav0908@crwdctrl.6smlz12.mongodb.net/?appName=crwdctrl,EMAIL_USER=karanjadhav0430@gmail.com,EMAIL_PASS=imfpwilyjzscquin,ADMIN_JWT_SECRET=8e16c3bde96dbd0843ba594ab09b18e69457f34c6d06999fb4cf3254973f8169,ADMIN_REFRESH_SECRET=your-secure-refresh-secret-key,CLOUDINARY_CLOUD_NAME=dyonimhgb,CLOUDINARY_API_KEY=364951443798767,CLOUDINARY_API_SECRET=i0F-jEG4V3n6vM_tlLtSCVx6bUI,GOOGLE_SERVICE_ACCOUNT_EMAIL=sheet-service-507@keen-incline-483004-g5.iam.gserviceaccount.com,GOOGLE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvZ3RXES5nOTyI\ndZ3pEn0PEo++plR1CmSEdjy72zB/QR5XC7tBhtsU9dtf9achwjk00K8l092uuYkO\nMK5416911pwgemxGJ8TU5cvEAeUyK5DBQJUmKK2ViwL3DxHHvaddkAZJR7TzFyEU\nUqUZUeu4kTvXxDVbJGzN3aunY0njPWsr0IuI+8P1jzVTE4LOUFLEgAsrd6XUzruW\nRs7/FaLlxAgsgbehUtQWDjCvZm8a8an/oLoy9wKCUirzRyknOzNOEgBcUk1EZN0x\n8Qny3ez4xSeDhubkF72eWhLs0ALwf0tPGFifRIvg70XDKpC0lDVDA9nl7tXzwZo4\nCqJwIxRTAgMBAAECggEAMp3IFNgAbAk4TqiiSP/s1sykbn/RH3VATHlSTWOTOyWv\ne68G+oHP9tx70dUxxawmlfcik+fvsNwZkN67emPDXl3v7+9kD1qqkkU95/IkEbZA\nr4PTho92iBD1ahYPK3SvN3C4X60xqnSiNxsiSYw6WaiPfFRCkWqRe1bckhE04T39\nIlV6Js/e77KhKnjkxv5cholM37npSsj10c00aAirHueyvH/ABdm0THVCjOgatYBi\nsYOLvgOgK3dXc2y7abKtISyQyr8dZ2vps9CZEWy92lnted+InnSchxJe+UrM44/e\ndbB3EodX0FPSmvtV7VTY0vtZykmX0xr40LXN3CdqAQKBgQDqcYS51Ybb7uGKuKqc\nDJcSDOKeuUMNaOTJwcCEYM2FT53DlKzkoi4+HFVE1scEruOqhW1Y4Sz+qtnbgWOU\nVm0o54ZbvuU1iNw0dqbewjXFVFkDl41c7UPBrtDTJPJu7X6HTJCanYIlDz7/xSmD\nLNIFXvz7Yd+IBzSja5S4TZCYeQKBgQC/iDr5K061yO5pqvNOt7fn2jBvygvBgjD5\nsrJj4zHD0avgebFaEWu0NqtKPyNtfJTRUdT8zeYx/GdgoC5RXyAIZjKZ50gp1kON\n4Q1Z8cT4VNTcLoGEyx2wn6Hbj9rlQI5iCiALEc7SyirRtC1wm4nK24YL6/kvNszp\nNmNO0bc4KwKBgBaVUsy35eK/sxgyy7R2fgLuHNJfVDcxeIB62nml/YYu8iqJ4tGv\nUbcH8arM6aTo1+NwMOVT44qwmIXNg/MhFCjRjJ6/18J9aYDgQRjKKnXUtzJiYeqm\nrFU26sS8FWJcHEkaNf++1m+NdWsb6fDJ231K9iGc/vRShV6MmWnbhuc5AoGBALqr\nSlbIV5kicQJ5g1KoCcwlQenh8F0zxwnFmMlzh3ADLNHFqQ1QRzlHwt/E84Fk1yG+\n8KdHAWCcUCDDXQEfhffJqu2GlTV5RzPDMKEF2mPxQdgqVz8WOySGIFj+NmgS5/Iz\nThGb1IhqUxs40MScQsp784QxAxZ6AXIV+Om7yScrAoGBAJc08jVYAxJ04rOp5K4E\nD6EQuuxkIXL8QfUctNM1P4hzfPa9NeZGN1kCagjTxenoxWa+Xh3QdLAj6ikGvUS+\nVZhQMgVgKE9osD6dqJc3ZAK+0jDDZPNEmkHXzKZ25YLDa9xC8wjIJqeDMJ2vcgxQ\n/BH4cmzxueFweNqtqfbQyEnB\n-----END PRIVATE KEY-----\n"'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY