steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'festbuzzzz-mvp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,ADMIN_EMAIL=crwdctrl.in@gmail.com,ADMIN_PASSWORD=CrwdCtrl0430,JWT_SECRET=festbuzzjwtsecretkey123456789abcdefghijklmnopqrstuvwxyz,MONGODB_URI=mongodb+srv://karan_lol:jadhav0908@crwdctrl.6smlz12.mongodb.net/?appName=crwdctrl,EMAIL_USER=karanjadhav0430@gmail.com,EMAIL_PASS=imfpwilyjzscquin,CLOUDINARY_CLOUD_NAME=dyonimhgb,CLOUDINARY_API_KEY=364951443798767,CLOUDINARY_API_SECRET=i0F-jEG4V3n6vM_tlLtSCVx6bUI,GOOGLE_SERVICE_ACCOUNT_EMAIL=sheet-service-507@keen-incline-483004-g5.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'GOOGLE_PRIVATE_KEY=projects/keen-incline-483004/secrets/google-private-key:latest'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/festbuzz-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY