/**
 * Register all Mongoose models at startup so refs and indexes are ready.
 */
require('../model/fest_organizer_model');
require('../model/student&participant');
require('../model/usermodel');
require('../model/event_model');
require('../model/competition_model');
require('../model/competition_registration_model');
require('../model/registration_model');
require('../model/platform_event_model');
require('../model/sports_model');
require('../model/run_club_model');
require('../model/trek_model');
require('../model/trek_community_model');
require('../model/trek_booking_model');
require('../model/trek_organizer_account_model');
require('../model/run_club_organizer_account_model');
require('../model/event_show_model');
require('../model/category_registration_model');
require('../model/notification_model');
require('../model/analytics_model');
require('../model/payment_order_model');
require('../model/cashfree_settlement_model');
require('../model/payment_refund_model');
require('../model/organizer_payout_model');
require('../model/reconciliation_import_model');
require('../model/payment_audit_log_model');
require('../model/coupon_model');
require('../model/coupon_usage_model');
require('../model/homepage_section_model');
require('../model/site_setting_model');
require('../model/audience_preset_model');
require('../model/notification_campaign_model');
require('../model/event_show_registration_model');
require('../model/run_club_manager_profile_invite_model');
require('../model/trek_community_manager_profile_invite_model');
require('../model/event_show_manager_profile_invite_model');
require('../modules/campus-hunt/models').registerModels();
