const express = require('express');

const userRoutes = require('../routers/userroute');
const studentRoutes = require('../routers/studentroute');
const festOrganizerRoutes = require('../routers/festOrganizerRoute');
const publicFestRoutes = require('../routers/publicFestRoute');
const competitionRoutes = require('../routers/competitionRoute');
const adminRoutes = require('../routers/adminRoute');
const adminPlatformEventRoutes = require('../routers/adminPlatformEventRoute');
const publicPlatformEventRoutes = require('../routers/publicPlatformEventRoute');
const publicTrekRoutes = require('../routers/publicTrekRoute');
const publicSportsRoutes = require('../routers/publicSportsRoute');
const publicEventShowRoutes = require('../routers/publicEventShowRoute');
const adminSportsRoutes = require('../routers/adminSportsRoute');
const adminRunClubRoutes = require('../routers/adminRunClubRoute');
const publicRunClubRoutes = require('../routers/publicRunClubRoute');
const adminTrekRoutes = require('../routers/adminTrekRoute');
const adminTrekCommunityRoutes = require('../routers/adminTrekCommunityRoute');
const publicTrekCommunityRoutes = require('../routers/publicTrekCommunityRoute');
const adminEventShowRoutes = require('../routers/adminEventShowRoute');
const categoryRegistrationRoutes = require('../routers/categoryRegistrationRoute');
const registrationRoutes = require('../routers/registrationRoute');
const paymentRoutes = require('../routers/paymentRoute');
const notificationRoutes = require('../routers/notificationRoute');
const qrRoutes = require('../routers/qrRoute');
const scannerRoutes = require('../routers/scannerRoute');
const analyticsRoutes = require('../routers/analyticsRoute');
const publicSearchRoutes = require('../routers/publicSearchRoute');
const publicHomepageSectionRoutes = require('../routers/publicHomepageSectionRoute');
const { authLimiter, paymentLimiter } = require('../middleware/rateLimiter');

const router = express.Router();

router.use('/users', authLimiter, userRoutes);
router.use('/students', studentRoutes);
router.use('/fest-organizer', festOrganizerRoutes);
router.use('/fests', publicFestRoutes);
router.use('/competitions', competitionRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/platform-events', adminPlatformEventRoutes);
router.use('/admin/sports', adminSportsRoutes);
router.use('/admin/run-clubs', adminRunClubRoutes);
router.use('/admin/treks', adminTrekRoutes);
router.use('/admin/trek-communities', adminTrekCommunityRoutes);
router.use('/trek-communities', publicTrekCommunityRoutes);
router.use('/admin/events', adminEventShowRoutes);
router.use('/platform-events', publicPlatformEventRoutes);
router.use('/treks', publicTrekRoutes);
router.use('/sports', publicSportsRoutes);
router.use('/events', publicEventShowRoutes);
router.use('/run-clubs', publicRunClubRoutes);
router.use('/category-registrations', categoryRegistrationRoutes);
router.use('/registrations', registrationRoutes);
router.use('/payment', paymentLimiter, paymentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/qr', qrRoutes);
router.use('/scanner', scannerRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/search', publicSearchRoutes);
router.use('/homepage-sections', publicHomepageSectionRoutes);
router.use('/page-sections', publicHomepageSectionRoutes);

module.exports = router;
