const express = require('express');

const userRoutes = require('../routers/userroute');
const studentRoutes = require('../routers/studentroute');
const festOrganizerRoutes = require('../routers/festOrganizerRoute');
const festOrganizerPortalRoutes = require('../routers/festOrganizerPortalRoute');
const publicFestRoutes = require('../routers/publicFestRoute');
const competitionRoutes = require('../routers/competitionRoute');
const adminRoutes = require('../routers/adminRoute');
const adminPlatformEventRoutes = require('../routers/adminPlatformEventRoute');
const publicPlatformEventRoutes = require('../routers/publicPlatformEventRoute');
const publicTrekRoutes = require('../routers/publicTrekRoute');
const publicSportsRoutes = require('../routers/publicSportsRoute');
const publicEventShowRoutes = require('../routers/publicEventShowRoute');
const adminSportsRoutes = require('../routers/adminSportsRoute');
const adminRunClubRoutes = require('../routers/adminRunClubRoute');
const publicRunClubRoutes = require('../routers/publicRunClubRoute');
const adminTrekRoutes = require('../routers/adminTrekRoute');
const adminTrekOrganizerRoutes = require('../routers/adminTrekOrganizerRoute');
const adminFestOrganizerRoutes = require('../routers/adminFestOrganizerRoute');
const adminRunClubOrganizerRoutes = require('../routers/adminRunClubOrganizerRoute');
const adminTrekCommunityRoutes = require('../routers/adminTrekCommunityRoute');
const publicTrekCommunityRoutes = require('../routers/publicTrekCommunityRoute');
const adminEventShowRoutes = require('../routers/adminEventShowRoute');
const categoryRegistrationRoutes = require('../routers/categoryRegistrationRoute');
const registrationRoutes = require('../routers/registrationRoute');
const paymentRoutes = require('../routers/paymentRoute');
const notificationRoutes = require('../routers/notificationRoute');
const qrRoutes = require('../routers/qrRoute');
const scannerRoutes = require('../routers/scannerRoute');
const trekOrganizerRoutes = require('../routers/trekOrganizerRoute');
const runClubOrganizerRoutes = require('../routers/runClubOrganizerRoute');
const adminEventShowOrganizerRoutes = require('../routers/adminEventShowOrganizerRoute');
const eventShowOrganizerRoutes = require('../routers/eventShowOrganizerRoute');
const analyticsRoutes = require('../routers/analyticsRoute');
const publicSearchRoutes = require('../routers/publicSearchRoute');
const publicHomepageSectionRoutes = require('../routers/publicHomepageSectionRoute');
const publicHomeRoutes = require('../routers/publicHomeRoute');
const publicConfigRoutes = require('../routers/publicConfigRoute');
const mapsRoutes = require('../routers/mapsRoute');
const adminSiteSettingRoutes = require('../routers/adminSiteSettingRoute');
const adminCouponRoutes = require('../routers/adminCouponRoute');
const adminNotificationRoutes = require('../routers/adminNotificationRoute');
const adminPaymentSettlementRoutes = require('../routers/adminPaymentSettlementRoute');
const communityFollowRoutes = require('../routers/communityFollowRoute');
const campusHuntRoutes = require('../routers/campusHuntRoute');
const { authLimiter, paymentLimiter } = require('../middleware/rateLimiter');

const router = express.Router();

router.use('/users', authLimiter, userRoutes);
router.use('/students', studentRoutes);
// Legacy User-role fest CRUD + check-in (scanner account portal)
router.use('/organizer/fests', festOrganizerRoutes);
// Dedicated fest organizer portal (FestOrganizerAccount JWT)
router.use('/fest-organizer', festOrganizerPortalRoutes);
router.use('/fests', publicFestRoutes);
router.use('/competitions', competitionRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/platform-events', adminPlatformEventRoutes);
router.use('/admin/sports', adminSportsRoutes);
router.use('/admin/run-clubs', adminRunClubRoutes);
router.use('/admin/treks', adminTrekRoutes);
router.use('/admin/trek-organizers', adminTrekOrganizerRoutes);
router.use('/admin/fest-organizers', adminFestOrganizerRoutes);
router.use('/admin/run-club-organizers', adminRunClubOrganizerRoutes);
router.use('/admin/event-organizers', adminEventShowOrganizerRoutes);
router.use('/admin/trek-communities', adminTrekCommunityRoutes);
router.use('/admin/site-settings', adminSiteSettingRoutes);
router.use('/admin/coupons', adminCouponRoutes);
router.use('/admin/notifications', adminNotificationRoutes);
router.use('/admin/payments', adminPaymentSettlementRoutes);
router.use('/trek-communities', publicTrekCommunityRoutes);
router.use('/admin/events', adminEventShowRoutes);
router.use('/platform-events', publicPlatformEventRoutes);
router.use('/treks', publicTrekRoutes);
router.use('/sports', publicSportsRoutes);
router.use('/events', publicEventShowRoutes);
router.use('/run-clubs', publicRunClubRoutes);
router.use('/category-registrations', categoryRegistrationRoutes);
router.use('/registrations', registrationRoutes);
router.use('/payment', paymentLimiter, paymentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/qr', qrRoutes);
router.use('/trek-organizer', trekOrganizerRoutes);
router.use('/run-club-organizer', runClubOrganizerRoutes);
router.use('/event-organizer', eventShowOrganizerRoutes);
router.use('/scanner', scannerRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/home', publicHomeRoutes);
router.use('/config', publicConfigRoutes);
router.use('/search', publicSearchRoutes);
router.use('/homepage-sections', publicHomepageSectionRoutes);
router.use('/page-sections', publicHomepageSectionRoutes);
router.use('/maps', mapsRoutes);
router.use('/follows', communityFollowRoutes);
router.use('/campus-hunt', campusHuntRoutes);

module.exports = router;
