/** Admin + portal copy for run-club (sports) vs event-community (events) organizers. */
export const COMMUNITY_ORGANIZER_HUB_COPY = {
    sports: {
        hub: 'sports',
        title: 'Run Club Organizers',
        subtitle: 'Approve club logins, and choose which app emails see Club manager in Profile. Approved organizers whose email matches their CrwdCtrl login also see Club manager automatically.',
        emptyClubs: 'Publish a run club under Admin → Sports / Run Clubs first, then you can add a club organizer.',
        profileSectionTitle: 'Approve Profile → Club manager',
        profileSectionHint: 'These CrwdCtrl user emails see Club manager in Profile and can request signup. Separately approve the organizer username under Organizer accounts.',
        profileInviteToast: 'Email approved for Profile → Club manager',
        profileInviteRemove: 'Remove from Club manager profile access?',
        approveToast: 'Approved — they can sign in. Club manager also shows in Profile if this email matches their CrwdCtrl login.',
        clubFieldLabel: 'Run club',
        clubSelectPlaceholder: 'Select run club',
        publishHint: 'Admin → Sports / Run Clubs',
        signupUrlSuffix: '',
        signupLoginPath: '/run-club-organizer/login',
        signupPath: '/run-club-organizer/signup',
        profileLabel: 'Club manager',
        icon: 'footprints',
    },
    events: {
        hub: 'events',
        title: 'Event Community Organizers',
        subtitle: 'Add invited emails and share the login or signup link. Organizers create their account and sign in — no approval email.',
        emptyClubs: 'Publish an event community under Admin → Events first, then add an organizer for it.',
        profileSectionTitle: 'Approve Profile → Community organizer',
        profileSectionHint: 'These emails can create an organizer account. Share the signup or login link manually — we do not email them.',
        profileInviteToast: 'Email approved — share the signup link manually',
        profileInviteRemove: 'Remove from Community organizer profile access?',
        approveToast: 'Approved — they can sign in now. Share the login link if needed.',
        clubFieldLabel: 'Event community',
        clubSelectPlaceholder: 'Select community',
        publishHint: 'Admin → Events',
        signupUrlSuffix: '',
        signupLoginPath: '/event-community-organizer/login',
        signupPath: '/event-community-organizer/signup',
        profileLabel: 'Community organizer',
        icon: 'users',
    },
};
