/** Admin + portal copy for run-club (sports) vs event-community (events) organizers. */
export const COMMUNITY_ORGANIZER_HUB_COPY = {
    sports: {
        hub: 'sports',
        title: 'Run Club Organizers',
        subtitle: 'Approve club logins, and choose which app emails see Club manager in Profile. Approved organizers whose email matches their CrwdCtrl login also see Club manager automatically.',
        emptyClubs: 'Publish a run club under Admin → Sports / Run Clubs first, then you can add a club organizer.',
        profileSectionTitle: 'Approve Profile → Club manager',
        profileSectionHint: 'These CrwdCtrl user emails see Club manager in Profile and can request signup. Separately approve the organizer username under Organizer accounts.',
        profileInviteToast: 'Email approved for Profile → Club manager',
        profileInviteRemove: 'Remove from Club manager profile access?',
        approveToast: 'Approved — they can sign in. Club manager also shows in Profile if this email matches their CrwdCtrl login.',
        clubFieldLabel: 'Run club',
        clubSelectPlaceholder: 'Select run club',
        publishHint: 'Admin → Sports / Run Clubs',
        signupUrlSuffix: '',
        profileLabel: 'Club manager',
        icon: 'footprints',
    },
    events: {
        hub: 'events',
        title: 'Event Community Organizers',
        subtitle: 'Approve community organizer logins and invite emails for Delulu-style event communities. Organizers create their account at the signup link, then you approve here.',
        emptyClubs: 'Publish an event community under Admin → Events first, then add an organizer for it.',
        profileSectionTitle: 'Approve Profile → Community organizer',
        profileSectionHint: 'These emails can create an organizer account for an event community. After signup, approve their username under Organizer accounts — we email them when approved.',
        profileInviteToast: 'Email approved — invite sent with signup link',
        profileInviteRemove: 'Remove from Community organizer profile access?',
        approveToast: 'Approved — login email sent. They can manage guests, scan & notify.',
        clubFieldLabel: 'Event community',
        clubSelectPlaceholder: 'Select community',
        publishHint: 'Admin → Events',
        signupUrlSuffix: '?hub=events',
        profileLabel: 'Community organizer',
        icon: 'users',
    },
};
