export {
    getFcmTokenIfGranted,
    requestNotificationPermission,
    onForegroundMessage,
    firebaseReady,
    signInWithGoogle,
    signInWithFacebook,
    registerWithEmail,
    loginWithEmail,
    sendVerificationEmail,
    verifyEmail,
    onAuthStateChange,
    getCurrentUser,
    handleRedirectResult,
    isMobileDevice,
    auth,
    app,
    analytics,
    performance,
    signOut,
} from './firebase/index.js';
