const express = require('express');
const adminAuth = require('../../middleware/adminAuth');
const { authenticateToken, optionalAuthenticateToken } = require('../../middleware/authmiddleware');
const controller = require('./controller');
const hostController = require('./hostController');

const publicRouter = express.Router();
publicRouter.get('/colleges', controller.listColleges);
publicRouter.get('/rankings', controller.rankings);
publicRouter.get('/', controller.listGames);
publicRouter.post('/host-requests', optionalAuthenticateToken, controller.createHostRequest);
publicRouter.get('/host-permissions/confirm/:token', hostController.confirmAuthorityPermission);
publicRouter.post('/host-access/login', hostController.operatorLogin);
publicRouter.post('/host-access/:gameId/operations/:action', hostController.operatorOperation);
publicRouter.use('/host', authenticateToken);
publicRouter.get('/host/profile', authenticateToken, hostController.getHostProfile);
publicRouter.put('/host/profile', authenticateToken, hostController.saveHostProfile);
publicRouter.get('/host/campus-hunts', authenticateToken, hostController.listHostedGames);
publicRouter.post('/host/campus-hunts', authenticateToken, hostController.requireHostingEnabled, hostController.createHostedGame);
publicRouter.put('/host/campus-hunts/:gameId', authenticateToken, hostController.updateHostedGame);
publicRouter.post('/host/campus-hunts/:gameId/permission-document', authenticateToken, hostController.permissionUploadMiddleware, hostController.uploadPermissionDocument);
publicRouter.put('/host/campus-hunts/:gameId/permission', authenticateToken, hostController.savePermission);
publicRouter.post('/host/campus-hunts/:gameId/submit', authenticateToken, hostController.submitHostedGame);
publicRouter.get('/host/campus-hunts/:gameId/dashboard', authenticateToken, hostController.getHostDashboard);
publicRouter.post('/host/campus-hunts/:gameId/control-session', authenticateToken, hostController.createHostControlSession);
publicRouter.get('/host/campus-hunts/:gameId/setup', authenticateToken, hostController.getHostSetup);
publicRouter.patch('/host/campus-hunts/:gameId/setup', authenticateToken, hostController.updateHostSetup);
publicRouter.patch('/host/campus-hunts/:gameId/setup/challenges/:challengeId', authenticateToken, hostController.updateHostChallenge);
publicRouter.post('/host/campus-hunts/:gameId/operators', authenticateToken, hostController.createOperator);
publicRouter.delete('/host/campus-hunts/:gameId/operators/:grantId', authenticateToken, hostController.revokeOperator);
publicRouter.post('/host/campus-hunts/:gameId/operations/:action', authenticateToken, hostController.hostOperation);
publicRouter.post('/host/campus-hunts/:gameId/teams/:teamId/:action', authenticateToken, hostController.hostTeamOperation);
publicRouter.post('/host/campus-hunts/:gameId/check-in-pack/activate', authenticateToken, hostController.activateCheckInPack);
publicRouter.post('/host/campus-hunts/:gameId/check-in-pack/sync', authenticateToken, hostController.syncCheckInPack);
publicRouter.post('/host/campus-hunts/:gameId/announcements', authenticateToken, hostController.sendAnnouncement);
publicRouter.post('/host/campus-hunts/:gameId/registrations/:registrationId/refunds', authenticateToken, hostController.hostRefundRequest);
publicRouter.get('/me/profile', authenticateToken, controller.getMyCollegeProfile);
publicRouter.get('/me/registrations', authenticateToken, controller.myRegistrations);
publicRouter.post('/me/registrations/:registrationId/refunds', authenticateToken, hostController.participantRefundRequest);
publicRouter.post('/me/registrations/:registrationId/disputes', authenticateToken, hostController.createDispute);
publicRouter.post('/:gameId/reports', authenticateToken, hostController.createReport);
publicRouter.post('/invites/:token/claim', authenticateToken, controller.claimInvite);
publicRouter.get('/passes/:id', authenticateToken, controller.getPass);
publicRouter.post('/:id/reservations', authenticateToken, controller.reserveRegistration);
publicRouter.get('/:id', controller.getGame);

const adminRouter = express.Router();
adminRouter.use(adminAuth);
adminRouter.get('/', controller.adminList);
adminRouter.get('/host-platform', hostController.adminHostPlatform);
adminRouter.patch('/hosts/:hostId', hostController.adminReviewHost);
adminRouter.patch('/permissions/:permissionId', hostController.adminReviewPermission);
adminRouter.get('/permissions/:permissionId/document', hostController.adminRevealPermissionDocument);
adminRouter.patch('/hosted-games/:gameId/review', hostController.adminReviewHostedGame);
adminRouter.post('/hosted-games/:gameId/turnout-decision', hostController.adminResolveTurnout);
adminRouter.post('/hosted-games/:gameId/emergency-stop', hostController.adminEmergencyStop);
adminRouter.post('/hosted-games/:gameId/clear-emergency-stop', hostController.adminClearEmergencyStop);
adminRouter.post('/hosted-games/:gameId/prizes', hostController.adminPrizeDisbursement);
adminRouter.post('/hosted-games/:gameId/payout', hostController.adminMarkPayout);
adminRouter.get('/hosted-games/:gameId/reconcile', hostController.adminReconcileHostedGame);
adminRouter.post('/refunds/:requestId/process', hostController.adminProcessRefund);
adminRouter.post('/disputes/:disputeId/resolve', hostController.adminResolveDispute);
adminRouter.post('/reports/:reportId/resolve', hostController.adminResolveHostReport);
adminRouter.post('/colleges', controller.adminCreateCollege);
adminRouter.put('/colleges/:id', controller.adminUpdateCollege);
adminRouter.post('/games', controller.adminCreateGame);
adminRouter.put('/games/:id', controller.adminUpdateGame);
adminRouter.put('/host-requests/:id', controller.adminUpdateHostRequest);
adminRouter.post('/registrations/:id/members/:memberId/approve-substitution', controller.adminApproveSubstitution);
adminRouter.post('/check-in', controller.adminCheckIn);
adminRouter.get('/results', controller.adminResults);
adminRouter.post('/results', controller.adminFinalizeResult);

module.exports = { publicRouter, adminRouter };
